### ISSUE TITLE
Motion permission?

### ISSUE THREAD

**Issue by nbawe** [maximbilan/iOS-CoreMotion-Example#3]
Do you know is it needed to ask permission before using altimeter or accelerometer data?

**Comment by maximbilan** [comment]
Yes, it's needed. You can check out the information from [Apple](https://developer.apple.com/documentation/coremotion) docs.

> An iOS app linked on or after iOS 10.0 must include usage description keys in its Info.plist file for the types of data it needs. Failure to include these keys will cause the app to crash. To access motion and fitness data specifically, it must include NSMotionUsageDescription.

**Comment by nbawe** [comment]
Thank you for the answer - if I ran your app. There was no such key in Info.plist, but app still did not crash. 
How is that possible?

**Comment by maximbilan** [comment]
> Thank you for the answer - if I ran your app. There was no such key in Info.plist, but app still did not crash.
> How is that possible?

This code was created 5 years ago, I can't give any guarantees on this code, because maybe there was a lot of changes in iOS SDK.

**Comment by nbawe** [comment]
If your code doesn’t give errors is it possible that CMMotionManager and CAAltimeter is not considered as sensitive privacy information?
